spring:
  application:
    name: A2_QuyetDX_HE186796_SE1941JV

  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=FUNewsManagementSBA301_v2;encrypt=true;trustServerCertificate=true;}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

server:
  port: 8080
