spring:
  application:
    name: Lab03_QuyetDXHE186796

  datasource:
    url: jdbc:sqlserver://localhost:1435;databaseName=employee_management;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Quyet@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080
