spring:
  application:
    name: Lab04_QuyetDXHE186796
  datasource:
    url: jdbc:sqlserver://localhost:1435;databaseName=OrchidDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Quyet@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
